### PR TITLE
Dont approve this. Just for experiement using github fork/pull

### PR DESCRIPTION
**Pull request by zhongh**
Dont approve this. Just for experiement using github fork/pull

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
Received an email that you had submitted a pull request. The BIGGEST issue is that this is off of the master branch and it shouldn't be. You need to create a new branch. Any pull requests against the branch will be denied.

**Comment by zednis** [comment]
Do you use the browser editor for this?

As Patrick said, normally we create a new branch and open a pull request to review/approve commits to that branch.  When the pull request is approved we merge the branch into master and close the branch.

**Comment by mrpatrickwest** [comment]
Also, these property files shouldn't be added to a commit. The property files are used in production and in the travis-ci build. If you add changes to the commit and submit a pull request then the travis-ci build will fail.

**Comment by zednis** [comment]
Patrick, I suspect Hao used the browser-based file editor.  You have the option to create a pull request from the single edit.  It basically creates an unnamed branch for the single proposed commit.  If we don't approve the pull request this commit will not be applied to master.

This feature is useful for small edits to single files (think readme updates).

**Comment by mrpatrickwest** [comment]
So for this pull request all we have to do is "Close and comment"? That way the pull request is closed and we won't see it?

**Comment by zednis** [comment]
Patrick, property files should be a part of the repo.  The startup script docker uses sed to update the property files with values from environment variables.

addendum - I don't think the docker script updates build.properties as nothing in it should change between dev/test/prod environments.

**Comment by zednis** [comment]
Yeah, if we comment and close without doing a merge this should be closed down properly.

**Comment by mrpatrickwest** [comment]
This was a test pull request to get Hao used to the process.
1. Always create a branch for your work. No work should be done in master
2. The property files, though part of the repo, and need to be updated for local work, shouldn't be added to a commit unless needed.

**Comment by zednis** [comment]
Ah, nevermind. Hao did not not the browser edit and unnamed branch - he forked the repo and is doing a pull request to push a commit from the master branch of his forked repository to the parent repository.

That is also an acceptable way to do pull requests.

**Pull request closed without merging**
