### PR TITLE
Repository website n online catalog clickable

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Added xml and ftl to make the two fields clickable

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
@zednis @zhonghao1014 @am-e 

When you all get a chance could you take a look at this. Custom display of websites for repositories. Thanks!

**Comment by zednis** [comment]
is it live on a test site?

**Comment by mrpatrickwest** [comment]
Yes ... apologies. Thought I had already posted a comment.

https://dco.tw.rpi.edu/vivo/display/aa39092b-00b5-4c92-8027-dd979dbc343e
https://dco.tw.rpi.edu/vivo/display/a39d2d01-53e7-4105-904e-c194d2234239

**Comment by zednis** [comment]
Looks good! :shipit:

**Comment by zhongh** [comment]
Looks good!

**Pull request merged**
