### PR TITLE
Display, Add, Remove, Modify the list of Creators and Contributors on Datasets

### PR DESCRIPTION
**Pull request by mrpatrickwest**

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
The main changes are to PropertyConfig.n3 which adds the entries for custom display and entry of creators and contributors, the changes to dcodata.ttl and dcodata-vivo.ttl which updates the Creator and Contributor classes to actually be usable in VIVO, and all.properties for locale variables used in the two different custom forms.

The other 14 files can be split in 2, half for creators and half for contributors. The listview files pertain to displaying the contributors and creators on the dataset page. The others are related to adding, modifying, rearranging and deleting creators and contributors from a custom form.

Could probably combine the js and css files into one and just use it, but it was easier to get it set up like this and in the short window that we have.

**Comment by mrpatrickwest** [comment]
Did more testing on udco and everything seems to be working just fine. The RDF is looking good.

Steps for getting the RDF correct
1. pull the changes for dco-vivo and dco-ontology (we'll only work with dco-vivo here)
2. sudo /etc/init.d/tomcat6 stop
3. mkdir /home/pwest/backups/vivo-2016mmdd
3.5. mysqldump -uroot -p vivo > /home/pwest/backups/vivo-2016mmdd/vivo.sql
4. sudo mv /usr/share/tomcat6/webapps/vivo\* /home/pwest/backups/vivo-2016mmdd/
5. sudo ant all
6. sudo chown -R tomcat:tomcat /usr/share/tomcat6/webapps/vivo*
7. sudo /etc/init.d/tomcat6 start
8. Watch the logs and wait until it's done starting
9. Watch the logs and let it finish updating inferences and indexes
10. I have 4 .n3 files that we need to use to add/remove rdf
    a. remove rmcreators.n3
    b. remove rmcontributors.n3
    c. remove duptomcat.n3
    d. add mvcreators.n3
11. Unfortunately we're not done there. There are probably going to be RDF in the vitro-kb-inf Jena Model that doesn't get removed through the user interface, or programatically. So we have to muck with the model.
    a. go to the ingest page from the sysadmin page
    b. find the vitro-kb-inf model
    c. save the model (creates a file called ingest in Downloads folder)
    d. edit the ingest file and change dco:Creator to dcodata:Creator
    e. Copy the full path of the jena model (that ends with vitro-kb-inf)
    f. clear statements for that model (also removes the model)
    g. let vivo re-inference and re-index
    h. re-create the vitro-kb-info model using the copied full path from e
    i. load statements using the ingest file, type turtle
    j. let vivo re-inference and re-index

And we should be done

Queries to use to verify the RDF looks good.
1. Check to make sure there aren't any two mostSpecificType
`
select ?s where { ?s <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType> <http://vivoweb.org/ontology/core#Relationship> .
?s <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType> dco:Creator . }
`
1. Make sure the dataset looks good
   `
   select ?g ?p ?o where { graph ?g { <http://info.deepcarbon.net/individual/smrh3p05urn90j6b8trja653kq> ?p ?o } }
   `
2. Make sure the role looks good
   `
   select ?g ?p ?o where { graph ?g { <http://info.deepcarbon.net/individual/hn2hejjt69vqdrpvj03g3lp5nr> ?p ?o } }
   `
3. Make sure there aren't any references to dco:Creator
   `
   select ?g ?s ?p where { graph ?g { ?s ?p dco:Creator } }
   `

and

`
select ?g ?p ?o where { graph ?g { dco:Creator ?p ?o  } }
`

**Comment by zednis** [comment]
I was able to add, remove, reorder, and create a contributor or creator to a dataset.

edit: tested for both People and Organizations.

One thing I did notice is the suggestion text in the Last name field for both creator and contributor includes "undefined" (e.g. text is _Select an existing Creator undefined_).  My guess is the inclusion of "undefined" is not intended.

screen shot 2016-06-24 at 10 49 44 am

**Comment by mrpatrickwest** [comment]
This is a general problem in VIVO. If I go to an author list for a publication and click to add a new person it shows "Select an existing Author undefined"

The variable that it's looking for is helpTextAdd, which is defined as part of the i18nStrings variables in the ftl

`
var i18nStrings = {
    creatorNameWrapperTitle: '${i18n().drag_drop_reorder_creators}',
    reorderCreatorsAlert: '${i18n().reordering_creators_failed}',
    removeCreatorshipMessage: '${i18n().confirm_creator_removal}',
    removeCreatorshipAlert: '${i18n().error_processing_creator_request}',
    creatorTypeText: '${i18n().creator_capitalized}',
    organizationTypeText: '${i18n().organization_capitalized}',
    helpTextSelect: '${i18n().select_an_existing}',
    helptextAdd: '${i18n().or_add_new_one}'
`

but if you look for or_add_new_one in the all.properties file you come up empty.

I'm adding or_add_new_one to our all.properties files and make it "or add a new one"

**Pull request merged**
