### PR TITLE
adding submodule facetview2 and custom css to dco theme

### PR DESCRIPTION
**Pull request by zednis**

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
let's go ahead and get this installed on udco with, just copying over the css and js and facetview2 files into the right place for now, modify the vivo page to use that and make sure it all works. Sound good?

**Comment by zednis** [comment]
I can do that easily enough on UDCO.

Done already on prod :-)

**Comment by mrpatrickwest** [comment]
Oh ... well :shipit:

**Comment by zednis** [comment]
;-)  we should make the change on UDCO anyway.  I added the files to the theme on deepcarbon and verified all the files were accessible before I changed the embedded HTML.

I'll merge and close this now and make the UDCO change tonight.

**Pull request merged**
