### PR TITLE
Add docker config for fuseki container

### PR DESCRIPTION
**Pull request by zednis**
I have added the configuration for a docker container that runs the fuseki instance associated with the VIVO site.

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
Does the fuseki installation put anything in /etc/init.d to have it run automatically after a machine restart? Or the fact that it's in a docker container takes care of this?

**Comment by jpmccu** [comment]
Is there any chance of publishing some of these containers to the docker
container repo? They sound really helpful for lots of projects.

Jim

**Comment by zednis** [comment]
@mrpatrickwest docker containers (or at least this one) do not use /etc/init.d.  This container is using runit instead.  When the container starts it invokes the command `/sbin/my_init` which runs in the foreground and invokes run scripts found in /etc/service.

The fuseki init script is installed in the container at `/etc/service/fuseki/run`.  It is called by runit (with no parameters) and it exec's the command `${FUSEKI_HOME}/run-fuseki run`

**Comment by zednis** [comment]
@jimmccusker I think that is a good idea.  This is a modified version of fuseki that has some non-standard dependencies so it can access the VIVO SDB triplestore.

My intention is to setup a TWC docker image repository for highly-customized images and to make use of the docker hub for more general images (standard fuseki, s2s, etc)

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
