### PR TITLE
Remove external concept vocabularies

### PR DESCRIPTION
**Pull request by am-e**
For now, the list of external concept sources is hidden and we can only add concepts from DCO.

### CODE REVIEW

**Comment by am-e** [comment]
- Removed the label "External Vocabulary Services".
  screen shot 2016-02-15 at 10 19 05 am

**Comment by mrpatrickwest** [comment]
which test server is this installed on?

**Comment by am-e** [comment]
It's on https://dco.tw.rpi.edu/vivo/login

**Comment by mrpatrickwest** [comment]
:+1: 

@olyerickson @xgmachina @zhonghao1014 
Please review this change. Go to https://dco.tw.rpi.edu/vivo/login and use the root login (ask if you don't know it), go to your profile page then add a research area. You won't see that list of external vocabulary services.

**Comment by zednis** [comment]
:+1: I tested on dco.tw and did not see any external vocabulary services in the add/edit research areas form for my profile.

**Comment by zednis** [comment]
What if we want to add an external service of our choosing to the form?  It would be nice to not have the default external services as options but be able to include new options of our own choosing.

@mrpatrickwest what do you think?  Are there any external vocabularies that it would make sense to include?  What do you think about perhaps having the DCO vocabulary as an external vocabulary?

**Comment by am-e** [comment]
@zednis I think that is definitely the idea. For now we have commented out the external vocabulary sources but we should (on another ticket) look into creating a DCO vocabulary source, perhaps in relation to the glossary work?

**Comment by zednis** [comment]
@am-e that is definitely what I am thinking.  I don't want to introduce scope creep to this ticket, but since we are looking at the code right now related to external vocabularies, is these an alternative way to remove the current default external vocabularies that will allow us to introduce our own external vocabularies (if needed) later?

I guess what I am asking is if there is an alternative solution to this ticket where we don't comment out the part of the template that shows external vocabularies but instead change our configuration (or code) such that these external vocabularies are not available to be shown?

**Comment by am-e** [comment]
@zednis Actually there is, there is a class ConceptSearchServiceUtils which builds the list of external vocabularies that are available. When I had disabled these, the region in the template still appeared but with no sources to choose from so I decided to comment it out.

I think you are right, this would be a good time to investigate creating our own external source and adding it rather than hiding the whole thing. @mrpatrickwest what do you think?

**Comment by mrpatrickwest** [comment]
Definitely out of the scope of this ticket. But yes, I agree that we should start looking into it.

Are we talking about creating a service for our own vocabulary and removing them from VIVO? I can definitely see adding one in the future for the science vocabularies we discussed in a previous meeting.

**Comment by mrpatrickwest** [comment]
For this ticket I say :shipit:

**Comment by zednis** [comment]
I am not suggesting we add an external vocabulary for this ticket, but that we resolve this ticket in a manner where we are not hiding any and all external vocabularies.

edit: So I am not ready to say :shipit:  yet

**Comment by mrpatrickwest** [comment]
If we do add a service for a vocabulary we can uncomment the code. Since we don't have any external vocabulary services at the moment I think not displaying it is the way to go.

**Comment by zednis** [comment]
What is shown if we display it?

**Comment by am-e** [comment]
A heading "External Vocabulary Sources" and an empty <ul> which renders to
nothing.

**Comment by zednis** [comment]
@am-e Can you update the template to check if there are any vocabulary services and only show the heading and list if there are?

Instead of commenting it out for all cases let's have the template perform a check.

**Comment by am-e** [comment]
I'll try that out, will probably work.

**Comment by zednis** [comment]
@am-e :+1:

**Comment by am-e** [comment]
Alright, it works. The region is displayed only if the size of sources is larger than 0.
I pushed those changes to doc.tw, it should behave exactly the same though.

**Comment by zednis** [comment]
Great!  Thanks.

I am now happy if we :shipit:

**Comment by am-e** [comment]
Great, merging now.

**Pull request merged**
