### PR TITLE
Organization refactoring

### PR DESCRIPTION
**Pull request by zednis**
- [x] Add PortalGroup and Research Community to list of options from new 'member of' options
- [ ] Remove `dco:PortalGroup`
- [ ] Refactor `dco:ResearchCommunity` to be a subclass of `foaf:Group` and no longer a subclass of `foaf:Organization`

### CODE REVIEW

**Comment by zednis** [comment]
Potentially reduce the default non-DCO options for this property?  See the added file in this branch for the full list.

**Comment by zednis** [comment]
@olyerickson @mrpatrickwest

**Comment by zednis** [comment]
Here is the list of default organizations/groups/etc available when you create a new 'member of' relationship.

```
                "http://vivoweb.org/ontology/core#AcademicDepartment","Academic Department",
                "http://vivoweb.org/ontology/core#Association","Association",
                "http://vivoweb.org/ontology/core#Center","Center",
                "http://vivoweb.org/ontology/core#ClinicalOrganization","Clinical Organization",
                "http://vivoweb.org/ontology/core#College","College",
                "http://vivoweb.org/ontology/core#Committee","Committee",
                "http://vivoweb.org/ontology/core#Company","Company",
                "http://vivoweb.org/ontology/core#Consortium","Consortium",
                "http://vivoweb.org/ontology/core#CoreLaboratory","Core Laboratory",
                "http://vivoweb.org/ontology/core#Department","Department",
                "http://vivoweb.org/ontology/core#Division","Division",
                "http://vivoweb.org/ontology/core#ExtensionUnit","Extension Unit",
                "http://vivoweb.org/ontology/core#Foundation","Foundation",
                "http://vivoweb.org/ontology/core#FundingOrganization","Funding Organization",
                "http://vivoweb.org/ontology/core#GovernmentAgency","Government Agency",
                "http://xmlns.com/foaf/0.1/Group","Group",
                "http://vivoweb.org/ontology/core#Hospital","Hospital",
                "http://vivoweb.org/ontology/core#Institute","Institute",
                "http://vivoweb.org/ontology/core#Laboratory","Laboratory",
                "http://vivoweb.org/ontology/core#Library","Library",
                "http://purl.obolibrary.org/obo/OBI_0000835","Manufacturer",
                "http://vivoweb.org/ontology/core#Museum","Museum",
                "http://xmlns.com/foaf/0.1/Organization","Organization",
                "http://vivoweb.org/ontology/core#PrivateCompany","Private Company",
                "http://vivoweb.org/ontology/core#Program","Program",
                "http://vivoweb.org/ontology/core#Publisher","Publisher",
                "http://vivoweb.org/ontology/core#ResearchOrganization","Research Organization",
                "http://vivoweb.org/ontology/core#School","School",
                "http://vivoweb.org/ontology/core#Team","Team",
                "http://vivoweb.org/ontology/core#ServiceProvidingLaboratory","Service Providing Lab",
                "http://vivoweb.org/ontology/core#StudentOrganization","Student Organization",
                "http://purl.obolibrary.org/obo/ERO_0000565","Technology Transfer Office",
                "http://vivoweb.org/ontology/core#University","University"
```

**Comment by zednis** [comment]
We _may_ possibly have the following additional requirements (per @olyerickson)
- [ ] DCO teams that are not portal groups
- [ ] allow an instrument to be associated with a portal group (requirement source?)
- [ ] allow a DCO team to be associated with a portal group (requirement source?)
- [ ] allow a Research Community to be associated with a portal group

Are these new requirements?

PCW: These are no longer requirements as we will be getting rid of dco:PortalGroup

**Comment by mrpatrickwest** [comment]
- [ ] Remove dco:inOrganization in favor of property "member of"
- [ ] Migrate all existing dco:inOrganization to "member of"

**Comment by zednis** [comment]
- [ ] un-deprecate `vivo:contributingRole` (is the inverse of "member of" showing from a person page what orgs/groups/teams/etc they are members of)

**Comment by mrpatrickwest** [comment]
- [ ] Modify es ingest code
- [ ] Modify .rq and .xslt files (queries and translations)

**Comment by mrpatrickwest** [comment]
Updated ontology change document
https://docs.google.com/document/d/1f5k76aK1Kd1dWTshfwe9FP7L6wAwgwkKlxzrp0-W7BY/edit

**Comment by mrpatrickwest** [comment]
@zednis  Ready to ship?

**Pull request merged**
