### PR TITLE
slack notification to post to dco-ds channel

### PR DESCRIPTION
**Pull request by zednis**
Updated slack notification settings in Travis-CI config such that travis-ci notifications will be posted to the private dco-ds slack channel.

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
was there a problem with this? Curious what the change is for.

**Comment by zednis** [comment]
notifications were going to the travis-ci channel.  I proposed this change so the dco-vivo test results show up in just the dco-ds channel.  Hopefully, this will make build results more visible to project members that do not check the travis-ci channel.

**Comment by zednis** [comment]
... same idea as when we moved the dco-ds github notifications from showing up in a generic github channel to showing up in the dco-ds channel.

**Comment by mrpatrickwest** [comment]
makes sense ... :shipit:

**Pull request merged**
