### PR TITLE
Initial import of DCO modifications into DCO VIVO 3-tier build

### PR DESCRIPTION
**Pull request by zednis**

### CODE REVIEW

**Comment by zednis** [comment]
adding Han and Momo

@momochen 
@nahgnaw

**Comment by zednis** [comment]
adding Hao.

@zhonghao1014

**Comment by zednis** [comment]
The 3-tier build seems to be working using docker.

This is what I get after running the docker build:
screen shot 2015-05-18 at 8 49 38 am

Does anyone know a good way to test that the dco-added code is not blowing up?

**Comment by zednis** [comment]
When I opened the form to create a new instance of type vivo:Dataset from the admin page I got the following error:

```
2015-05-18 15:05:33,231 ERROR [runtime] Template processing error: "Error on line 9, column 1 in newIndividualForm.ftl\neditConfiguration.pageData.isPersonType is undefined.\nIt cannot be assigned to isPersonType"
Error on line 9, column 1 in newIndividualForm.ftl
editConfiguration.pageData.isPersonType is undefined.
It cannot be assigned to isPersonType
The problematic instruction:
----------
==> assignment: isPersonType=editConfiguration.pageData.isPersonType [on line 9, column 1 in newIndividualForm.ftl]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Error on line 9, column 1 in newIndividualForm.ftl
editConfiguration.pageData.isPersonType is undefined.
It cannot be assigned to isPersonType
    at freemarker.core.Assignment.accept(Assignment.java:111)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.MixedContent.accept(MixedContent.java:92)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.Environment.process(Environment.java:199)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper.processTemplate(TemplateProcessingHelper.java:58)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper.processTemplate(TemplateProcessingHelper.java:37)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.processTemplate(FreemarkerHttpServlet.java:502)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.processTemplateToString(FreemarkerHttpServlet.java:508)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doTemplate(FreemarkerHttpServlet.java:271)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doResponse(FreemarkerHttpServlet.java:239)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:111)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at edu.cornell.mannlib.vitro.webapp.controller.VitroHttpServlet.service(VitroHttpServlet.java:69)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doNonDisplayPage(PageRoutingFilter.java:110)
    at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doFilter(PageRoutingFilter.java:101)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.RequestModelsPrep.doFilter(RequestModelsPrep.java:115)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.URLRewriterFilter.doFilter(URLRewriterFilter.java:38)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.JSessionStripFilter.doFilter(JSessionStripFilter.java:60)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.produceBasicResponse(CachingResponseFilter.java:322)
    at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.doFilter(CachingResponseFilter.java:115)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.i18n.selection.LocaleSelectionFilter.doFilter(LocaleSelectionFilter.java:62)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:25)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.SessionTimeoutLimitingFilter.doFilter(SessionTimeoutLimitingFilter.java:39)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.StartupStatusDisplayFilter.doFilter(StartupStatusDisplayFilter.java:64)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
2015-05-18 15:05:33,283 ERROR [FreemarkerHttpServlet] edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper$TemplateProcessingException: TemplateException creating processing environment
edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper$TemplateProcessingException: TemplateException creating processing environment
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper.processTemplate(TemplateProcessingHelper.java:60)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper.processTemplate(TemplateProcessingHelper.java:37)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.processTemplate(FreemarkerHttpServlet.java:502)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.processTemplateToString(FreemarkerHttpServlet.java:508)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doTemplate(FreemarkerHttpServlet.java:271)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doResponse(FreemarkerHttpServlet.java:239)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:111)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at edu.cornell.mannlib.vitro.webapp.controller.VitroHttpServlet.service(VitroHttpServlet.java:69)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doNonDisplayPage(PageRoutingFilter.java:110)
    at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doFilter(PageRoutingFilter.java:101)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.RequestModelsPrep.doFilter(RequestModelsPrep.java:115)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.URLRewriterFilter.doFilter(URLRewriterFilter.java:38)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.JSessionStripFilter.doFilter(JSessionStripFilter.java:60)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.produceBasicResponse(CachingResponseFilter.java:322)
    at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.doFilter(CachingResponseFilter.java:115)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.i18n.selection.LocaleSelectionFilter.doFilter(LocaleSelectionFilter.java:62)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:25)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.SessionTimeoutLimitingFilter.doFilter(SessionTimeoutLimitingFilter.java:39)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at edu.cornell.mannlib.vitro.webapp.filters.StartupStatusDisplayFilter.doFilter(StartupStatusDisplayFilter.java:64)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: freemarker.core.InvalidReferenceException: Error on line 9, column 1 in newIndividualForm.ftl
editConfiguration.pageData.isPersonType is undefined.
It cannot be assigned to isPersonType
    at freemarker.core.Assignment.accept(Assignment.java:111)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.MixedContent.accept(MixedContent.java:92)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.Environment.process(Environment.java:199)
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper.processTemplate(TemplateProcessingHelper.java:58)
    ... 54 more
```

Our custom 3rd tier is overriding (with changes) the NewIndividualFormGenerator.java file.

**Comment by zednis** [comment]
@momochen, @nahgnaw 

Do we know which version of the NewIndividualFormGenerator class is the correct one to use for DCO VIVO?

[our version - NewIndividualFormGenerator.java](https://github.com/tetherless-world/dco-vivo/blob/admin/dcoModified/src/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/NewIndividualFormGenerator.java)

[vivo's version - NewIndividualFormGenerator.java](https://github.com/vivo-project/VIVO/blob/bbc2e9cf5bb77f3d0ac0c17b49ea6687433fe726/src/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/NewIndividualFormGenerator.java)

The  "newIndividualForm.ftl" template in the build is attempting to use a variable not available from our overridden copy of this class.  Perhaps the wrong copy of this template is ending up in the 3-tier build?

**Comment by nahgnaw** [comment]
I don't recall we touched this file (at least not for me). @momochen?

**Comment by zednis** [comment]
We are not overriding the newIndividualForm.ftl file.  This may be an issue of a file being included in our custom 3rd-tier classes when it should not.

In other words, the solution may be to remove this class from the custom 3rd-tier and use the default that we will pickup from the vivo submodule.

**Comment by zednis** [comment]
I looked at the version of this file that is being used in tetherless-world/VIVO and it does not match the version that we are including in our 3-tier build.  It does match the version in the vivo submodule.

https://github.com/tetherless-world/VIVO/blob/twc-rel-1.6.1/src/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/NewIndividualFormGenerator.java

I will remove this file from the 3rd tier.

**Comment by zednis** [comment]
@nahgnaw 

Did we make any changes to DefaultAddMissingIndividualFormGenerator.java?

[tehterless-world/VIVO's version](https://github.com/tetherless-world/VIVO/blob/twc-rel-1.6.1/src/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/DefaultAddMissingIndividualFormGenerator.java) differs from [tetherless-world/dco-vivo's version](https://github.com/tetherless-world/dco-vivo/blob/admin/dcoModified/src/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/DefaultAddMissingIndividualFormGenerator.java)

**Comment by nahgnaw** [comment]
We'll need @momochen to answer this. I cannot tell if we did.

**Comment by zednis** [comment]
Thanks Han.

Comparing the version of DefaultAddMissingIndividualFormGenerator.java in the tetherless-world/VIVO repository with the one in the 3rd tier and with the one in the vivo-project/VIVO repository I believe we should remove this file from the 3rd tier and pickup the copy from the vivo submodule.

**Comment by momochen** [comment]
I don't think we have ever touched the IndividualFormGenerator file before....

**Comment by zednis** [comment]
Thanks Momo, I have removed that file from the custom 3rd tier so the build will utilize the file from the vivo submodule.

**Comment by zednis** [comment]
I am going to deploy this branch on dcotest and then we can play around with it and determine if we can approve and merge this pull request.

**Comment by zednis** [comment]
I have deployed this branch of the dco-vivo 3-tier build to http://dcotest.tw.rpi.edu:19080/vivo/ (you will need to be inside the RPI network to see the webpage).

@mrpatrickwest do you think this branch is ready to merge into master?

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
