### PR TITLE
Error handling for missing DOI when adding publication to person

### PR DESCRIPTION
**Pull request by am-e**

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
I go to add a publication and sure enough the button is disabled. But it remains disabled even after I've entered a DOI. I'm using Google Chrome on my mac.

**Comment by zednis** [comment]
Weird.  I am now seeing the same behavior as Patrick but earlier I could click the "or import via DOI metadata" because I checked to see what happened when I submitted a bad DOI (I submitted "f").

... now I cannot run that test.

@am-e have there been any pushes to dco.tw in the time between when I and Patrick commented in the various tickets?

Also, there are a couple errors in the web console that may be related?
- customFormWithAutocomplete.js:691 Uncaught TypeError: Cannot read property 'find' of undefined
- Uncaught TypeError: Cannot read property 'substring' of undefined

**Comment by am-e** [comment]
@mrpatrickwest @zednis Yes, apologies, I'd been tinkering around and wasn't able to rebuild vivo after the last changes because I lost the VPN connection and the plane was taking off.

Now, the 'substring' error was there all along, but the 'find' error is thrown because I changed the id of the submit button on the 'import via doi' form. This also caused the button to lose the dco theme. I've managed to fix that and still have the solution work but with the theme you can't tell if the button is disabled or not. It's on dco.tw now.

**Comment by zednis** [comment]
@am-e You should be able to add a local CSS statement via <style></style> to the page via the JSF that grays out the button but does not override the entire DCO button theme.

```
<!-- in head -->
<style>
input[type="submit"]:disabled {
    background: #dddddd;
}
</style>
```

**Comment by am-e** [comment]
That sounds like a great idea, I'm figuring out where to add the css.

**Comment by am-e** [comment]
I had to add !important to the style to get it to override the style in wilma.css and it is working on dco.tw now.

**Comment by zednis** [comment]
👍 
@mrpatrickwest what do you think?

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
