### PR TITLE
Making the accessURL of a distribution clickable

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Modified the list view configuration for the dco:accessURL to use a new
.xml file specifically for the accessURL property. Added the xml, which
points to a new template file for the accessURL.

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
Works in both test and production. Verifying with Jesse to make sure his links are showing up

**Comment by mrpatrickwest** [comment]
Jesse has confirmed that his journal article has the access URL clickable

**Comment by zednis** [comment]
Just to verify, we were already overriding the list view config?

**Comment by mrpatrickwest** [comment]
correct

**Comment by zednis** [comment]
Interesting, I did not realize that.

Proposed update looks good.  :+1:

Are we going to do `dco:downloadURL` in this change as well?  Also, will we override the view for DCAT landingPage, accessURL, and downloadURL too?

**Comment by mrpatrickwest** [comment]
downloadURL example: https://info.deepcarbon.net/vivo/display/n140 ... DONE

No examples of the dcat properties. Should we wait until we need to do this?

**Comment by zednis** [comment]
Yeah, let's wait.  What we have so far is good and addresses the current need.

**Comment by zednis** [comment]
:shipit:

**Pull request merged**
